name: Build Linux artifacts

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        submodules: 'true'

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ vars.DOCKERPUBLICBOT_USERNAME }}
        password: ${{ secrets.DOCKERPUBLICBOT_WRITE_PAT }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        version: lab:latest
        driver: cloud
        endpoint: docker/default
        install: true

    - name: Build runtime for Linux
      run: docker buildx build --platform linux/amd64,linux/arm64 -f runtime-ubuntu.Dockerfile . --output type=local,dest=out-runtime

    - name: Build client library for Linux (glibc)
      run: docker buildx build --platform linux/amd64,linux/arm64 -f libwebgpu-glibc.Dockerfile . --output type=local,dest=out-client-glibc

    - name: Build client library for Linux (musl)
      run: docker buildx build --platform linux/amd64,linux/arm64 -f libwebgpu-musl.Dockerfile . --output type=local,dest=out-client-musl
